[package]
name = "pinci"
version = "0.1.0"
edition = "2018"

[dependencies]
cortex-m = "0.7.2"
rp2040-hal = { path = "../../rp-hal/rp2040-hal", version = "0.2.0"}
cortex-m-rt = { version = "0.6.14", optional = true }
embedded-time = "0.12.0"
usb-device= "0.2.8"
usbd-serial = "0.1.1"
usbd-hid = "0.5.0"
keyberon = {path = "./../../keyberon"}
panic-halt= "0.2.0"
embedded-hal ="0.2.5"
rp2040-boot2 = "0.1.2"

[features]
default = ["rt"]
rt = ["cortex-m-rt","rp2040-hal/rt"]

